# FindNFQueue.cmake
# autogenerated by copilot

# Search for the libnetfilter_queue library
find_library(NFQUEUE_LIBRARY
    NAMES netfilter_queue
    PATHS /usr/lib /usr/local/lib
)

# Check if the library was found
if(NOT NFQUEUE_LIBRARY)
    message(FATAL_ERROR "libnetfilter_queue library not found")
endif()

# Provide the library to the caller
set(NFQUEUE_LIBRARY ${NFQUEUE_LIBRARY} CACHE STRING "libnetfilter_queue library")

# Provide the include directory to the caller
set(NFQUEUE_INCLUDE_DIR "/usr/include" CACHE PATH "libnetfilter_queue include directory")
